### ISSUE TITLE
.money bo'limida no'tog'ri font-weight berilgan

### ISSUE THREAD

**Issue by Azizbek-Boyhamdamov** [Andarov/namanganliklar24#1]
Valyuta belgilarini font-weight 500 bo'lishi kerak ya'ni  .mark selectori uchun  https://github.com/Andarov/namanganliklar24/blob/0af4250b8b06d16c89eabee792b263b2bc13bcb6/css/styles.css#L96
Valyuta qiymati esa font-weight 400 bo'lishi kerak ya'ni  .monet selectori uchun https://github.com/Andarov/namanganliklar24/blob/0af4250b8b06d16c89eabee792b263b2bc13bcb6/css/styles.css#L100

Sizda esa ikkinchi valyuta belgisi va qiymati fw : 500 ; bo'lib qolgan  , birinchisi esa yoq https://github.com/Andarov/namanganliklar24/blob/0af4250b8b06d16c89eabee792b263b2bc13bcb6/css/styles.css#L88

**Comment by Andarov** [comment]
#fix
