### ISSUE TITLE
Lenta.ru nashriyotini  ikonkasi ko'rinmayabdi

### ISSUE THREAD

**Issue by Azizbek-Boyhamdamov** [Andarov/namanganliklar24#4]
Lenta.ru nashriyotini ikonkasi ko'rinmayabdi sababi srcset da 2x lik rasmi uchun rasm nomi no'tog'ri berilgan lenta@2x.jpg qilib ko'rsatilgan papkada esa  lenta2x.jpg papkadagi nomini o'zgartirib qo'ying https://github.com/Andarov/namanganliklar24/blob/0af4250b8b06d16c89eabee792b263b2bc13bcb6/index.html#L141

**Comment by Andarov** [comment]
#fix
