### ISSUE TITLE
`hr`    stillari maketdan farq qiladi..

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [Andarov/namanganliklar24#9]
![image](https://user-images.githubusercontent.com/99461357/158422211-48a4132b-c1c6-4948-9b43-3a0828ce4b98.png)

**Comment by Andarov** [comment]
#fix issue asossiz maket bilan bir xil 1px soli #d1d1d1 berilgan

**Comment by MIRZOULUGBEK9008** [comment]
Asosiz emas maketdan mutloq farq qilyapti men code ni aytmadim stillarni
aytdim..
